language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer --prefer-source --dev install

script: vendor/bin/phpunit --coverage-text --debug --verbose --testsuite unit

notifications:
  email:
    - pratushnyi@smartling.com
    - ploparev@smartling.com
